### ISSUE TITLE
Why tensorlfow in tags?

### ISSUE THREAD

**Issue by danilw** [blab-liuliang/echo#1231]
I dont get it...

**Comment by timi-liuliang** [comment]
Compiled TensorFlow lite in third-party library.  
https://github.com/timi-liuliang/echo/tree/master/thirdparty/google

https://www.tensorflow.org/lite/examples
At first, I want use the  model "Pose estimation" and "Gesture recognition" for user input

**Comment by danilw** [comment]
I see thanks for reply, I did not notice it when when looked.
